import {db,ref,get,push,set,onValue,runTransaction,serverTimestamp,sesion,administrador,SUPER,idFormulario,mensaje} from './formularios-firebase.js';
import {persona,recoger} from './censo-ui.js?v=20261001';
const C=window.Censo,F=window.Formularios,$=id=>document.getElementById(id);let id,def,grupoId,original=null,esEditor=false,guardando=false,secuencia=0,paso=1;
function mostrarPaso(n){paso=n;for(let i=1;i<=3;i++){$('paso'+i).hidden=i!==n;const indicador=document.querySelector('[data-paso="'+i+'"]');indicador.classList.toggle('completado',i<n);if(i===n)indicador.setAttribute('aria-current','step');else indicador.removeAttribute('aria-current');}$('progreso').textContent='Paso '+n+' de 3';$('paso'+n).querySelector('h2').focus();}
function validarPaso(n){const cont=$('paso'+n);for(const el of cont.querySelectorAll('[data-rol]')){const campo=C.campos.find(c=>c.rol===el.dataset.rol);el.setCustomValidity('');try{const error=F.validarValor(campo,el.value.trim());if(error)throw new Error(error);if(campo.rol==='fecha_nacimiento'&&el.value&&C.edad(el.value)===null)throw new Error('Revisa la fecha de nacimiento.');}catch(err){el.setCustomValidity(err.message);}if(!el.checkValidity()){el.closest('details')?.setAttribute('open','');el.reportValidity();return false;}}return true;}
$('continuar1').onclick=()=>{if(validarPaso(1)){mensaje('');mostrarPaso(2);}};
$('continuar2').onclick=()=>{if(validarPaso(2)){for(const ficha of $('personas').children){const cuerpo=ficha.lastElementChild;if(!Object.values(recoger(cuerpo)).some(v=>v))persona(cuerpo,'persona-'+(++secuencia),{parroquia:recoger($('responsable')).parroquia,comuna:recoger($('responsable')).comuna,comunidad:recoger($('responsable')).comunidad});}mensaje('');mostrarPaso(3);}};
$('volver2').onclick=()=>mostrarPaso(1);$('volver3').onclick=()=>mostrarPaso(2);
$('registro').addEventListener('input',ev=>ev.target.setCustomValidity?.(''));
$('registro').addEventListener('change',ev=>ev.target.setCustomValidity?.(''));
function contar(){$('contador').textContent=$('personas').children.length+' / 100 personas';$('agregar').disabled=$('personas').children.length>=100;}
function agregar(valores, clave){if($('personas').children.length>=100)return;const detalle=document.createElement('details');detalle.className='panel tarjeta-censo';detalle.dataset.clave=clave||Array.from({length:100},(_,i)=>C.clave(i+1)).find(k=>![...$('personas').children].some(d=>d.dataset.clave===k));detalle.open=true;const resumen=document.createElement('summary'),titulo=document.createElement('span'),quitar=document.createElement('button');quitar.type='button';quitar.textContent='Quitar';resumen.append(titulo,quitar);const ficha=document.createElement('div');detalle.append(resumen,ficha);$('personas').querySelectorAll('details').forEach(d=>d.open=false);$('personas').append(detalle);const responsable=recoger($('responsable'));persona(ficha,'persona-'+(++secuencia),valores||{parroquia:responsable.parroquia,comuna:responsable.comuna,comunidad:responsable.comunidad});const rotulo=()=>{titulo.textContent=C.nombre(recoger(ficha))||'Persona '+($('personas').children.length);};rotulo();ficha.oninput=rotulo;quitar.onclick=ev=>{ev.preventDefault();if(Object.values(recoger(ficha)).some(v=>v)&&quitar.textContent!=='Confirmar quitar'){quitar.textContent='Confirmar quitar';detalle.open=true;return;}detalle.remove();contar();};contar();detalle.scrollIntoView({block:'nearest',behavior:'smooth'});}
function comenzar(datos){persona($('ficha-responsable'),'responsable',datos?.responsable||{},$('responsable'));$('territorio-responsable').replaceChildren();for(const rol of ['parroquia','comuna','comunidad'])$('territorio-responsable').append($('ficha-responsable').querySelector('[data-rol="'+rol+'"]').closest('.campo')); $('personas').innerHTML='';secuencia=0;Object.entries(datos?.personas||{}).forEach(([k,p])=>agregar(p,k));if(!$('personas').children.length)agregar();$('gracias').hidden=true;$('contenido').hidden=false;contar();mostrarPaso(1);}
$('agregar').onclick=()=>agregar();$('otro').onclick=()=>{grupoId=null;original=null;esEditor=false;comenzar();};
$('registro').onsubmit=async ev=>{ev.preventDefault();if(guardando)return;if(paso<3){$('continuar'+paso).click();return;}for(let n=1;n<=3;n++){mostrarPaso(n);if(!validarPaso(n))return;}guardando=true;$('guardar').disabled=true;try{if(!def||(!esEditor&&!def.activo))throw new Error('Este censo cerró la recepción de nuevos grupos.');const responsable=recoger($('responsable')),listas=[...$('personas').children];const miembros=listas.map(d=>recoger(d.lastElementChild));C.validarGrupo(responsable,miembros);const personas=Object.fromEntries(listas.map((d,i)=>[d.dataset.clave,miembros[i]]));const payload={...(original?.archivado!==undefined?{archivado:original.archivado}:{}),responsable,personas,cantidad:miembros.length,creado_en:original?.creado_en??serverTimestamp(),actualizado_en:serverTimestamp(),version:1};grupoId=grupoId||push(ref(db,'censos_grupos/'+id)).key;const ruta=ref(db,'censos_grupos/'+id+'/'+grupoId);if(original){const r=await runTransaction(ruta,actual=>{if(actual===null||actual.actualizado_en===original.actualizado_en)return payload;return;},{applyLocally:false});if(!r.committed)throw new Error('Este grupo cambió en otra sesión. Abre de nuevo su ficha desde el panel antes de editar.');}else await set(ruta,payload);$('contenido').hidden=true;$('gracias').hidden=false;$('confirmacion').textContent=miembros.length+(miembros.length===1?' persona quedó vinculada a ':' personas quedaron vinculadas a ')+C.nombre(responsable)+'.';$('referencia').textContent='Referencia del grupo: '+grupoId;$('volver-panel').href='censo-panel.html?id='+id;$('volver-panel').hidden=!esEditor;$('otro').hidden=!!original;mensaje('');$('gracias').scrollIntoView({block:'start'});}catch(err){listasAbrir();mensaje(err.code==='PERMISSION_DENIED'?'No se pudo guardar: comprueba la recepción del censo y tu acceso.':err.code?'No se pudo guardar el grupo. Conservamos las fichas para que puedas reintentar.':err.message,'error');}finally{guardando=false;$('guardar').disabled=false;}};
function listasAbrir(){$('personas').querySelectorAll('details').forEach(d=>d.open=true);}
// Los controles obligatorios dentro de una ficha cerrada deben quedar visibles al validar.
$('registro').addEventListener('invalid',ev=>{ev.target.closest('details')?.setAttribute('open','');},true);
try{id=idFormulario();const user=await sesion(),admin=await administrador(user);grupoId=new URLSearchParams(location.search).get('grupo');if(grupoId&&!/^[A-Za-z0-9_-]{20}$/.test(grupoId))throw new Error('La referencia del grupo no es válida.');const snap=await get(ref(db,'censos_definiciones/'+id));def=snap.val();if(!def)throw new Error('El censo no está disponible.');esEditor=admin&&(user.email===SUPER||def.lectura==='administradores');if(grupoId){if(!esEditor)throw new Error('Necesitas permiso administrativo para corregir grupos.');original=(await get(ref(db,'censos_grupos/'+id+'/'+grupoId))).val();if(!original)throw new Error('No se encontró el grupo.');$('guardar').textContent='Guardar cambios del grupo';}else if(!def.activo||def.acceso==='administradores'&&!admin)throw new Error(!def.activo?'Este censo ha cerrado la recepción.':'Este censo requiere una sesión de administrador.');$('titulo').textContent=def.titulo;$('descripcion').textContent=def.descripcion;$('nombre-cabecera').textContent=def.titulo;document.title=def.titulo+' · Sala Situacional';$('carga').hidden=true;comenzar(original);onValue(ref(db,'censos_definiciones/'+id),s=>{def=s.val();if(def){$('titulo').textContent=def.titulo;$('nombre-cabecera').textContent=def.titulo;$('descripcion').textContent=def.descripcion;document.title=def.titulo+' · Sala Situacional';}if(!def||!def.activo&&!original){$('guardar').disabled=true;mensaje('La recepción del censo está cerrada. Tus fichas permanecen en pantalla.','error');}else if(!guardando)$('guardar').disabled=false;},()=>mensaje('No se pudo comprobar la recepción del censo.','error'));}catch(err){$('carga').hidden=true;mensaje(err.code?'No se pudo abrir el censo. Si es interno, inicia sesión primero.':err.message,'error');}
