import {db,ref,get,set,update,onValue,serverTimestamp,sesion,administrador,SUPER,idFormulario,mensaje} from './formularios-firebase.js';
import {enlaces,copiar} from './censo-ui.js?v=20260930-3';
import {dibujarHeaderPDF,dibujarFooterPDF} from './pdf-header.js';
const $=id=>document.getElementById(id),C=window.Censo,e=window.Formularios.escapar;let id,def,user,grupos={},seguimiento={},modo='grupos',pagina=1,seleccion=[],cargados=false,verArchivados=false;
const gruposVisibles=()=>Object.fromEntries(Object.entries(grupos).filter(([,g])=>!!g.archivado===verArchivados));
const filtros=()=>Object.fromEntries(['buscar','parroquia','comuna','comunidad','responsable','seguimiento','genero','edad_min','edad_max'].map(k=>[k==='seguimiento'?'estado':k,$(k).value]));
function opciones(k,valores,texto='Todos'){const valor=$(k).value;$(k).innerHTML=`<option value="">${texto}</option>`+[...new Set(valores)].filter(Boolean).sort((a,b)=>a.localeCompare(b,'es')).map(v=>`<option value="${e(v)}">${e(v)}</option>`).join('');$(k).value=valor;}
function actualizarOpciones(){const rows=C.filas(gruposVisibles(),seguimiento,modo);opciones('parroquia',rows.map(r=>r.persona.parroquia),'Todas');const parroquia=$('parroquia').value;const ambito=rows.filter(r=>!parroquia||r.persona.parroquia===parroquia);opciones('comuna',ambito.map(r=>r.persona.comuna),'Todas');opciones('comunidad',ambito.filter(r=>!$('comuna').value||r.persona.comuna===$('comuna').value).map(r=>r.persona.comunidad),'Todas');const anterior=$('responsable').value;$('responsable').innerHTML='<option value="">Todos</option>'+Object.entries(gruposVisibles()).sort((a,b)=>C.nombre(a[1].responsable).localeCompare(C.nombre(b[1].responsable),'es')).map(([key,r])=>`<option value="${key}">${e(C.nombre(r.responsable)+' · '+C.documento(r.responsable))}</option>`).join('');$('responsable').value=anterior;}
function badge(v){return `<span class="${v==='Sí'?'badge-si':v==='No'?'badge-no':'estado'}">${e(v||'Sin marcar')}</span>`;}
function filtrosInvalidos(texto){seleccion=[];$('total').textContent='Revisa los filtros de edad';$('filas').innerHTML='<tr><td colspan="10">'+e(texto)+'</td></tr>';['excel','pdf','csv','pdf-resumen','pdf-asistencia','pdf-fichas'].forEach(k=>$(k).disabled=true);mensaje(texto,'error');}
function pintar(){actualizarOpciones();const todas=C.filas(gruposVisibles(),seguimiento,modo);const f=filtros();for(const k of ['edad_min','edad_max']){if(f[k]!==''&&(!Number.isInteger(Number(f[k]))||Number(f[k])<0||Number(f[k])>120)){filtrosInvalidos('La edad debe ser un número entero entre 0 y 120.');return;}}if(f.edad_min!==''&&f.edad_max!==''&&Number(f.edad_min)>Number(f.edad_max)){filtrosInvalidos('La edad mínima no puede superar la máxima.');return;}if($('mensaje').textContent.startsWith('La edad'))mensaje('');seleccion=C.filtrar(todas,f);const max=Math.max(1,Math.ceil(seleccion.length/25));pagina=Math.min(pagina,max);const nPersonas=Object.values(gruposVisibles()).reduce((n,g)=>n+g.cantidad,0);const duplicadas=C.filas(gruposVisibles(),seguimiento).length-new Set(C.filas(gruposVisibles(),seguimiento).map(r=>C.documento(r.persona))).size;
  const estadistica=C.resumen(seleccion);$('metricas').innerHTML=[['Responsables en el censo',Object.keys(gruposVisibles()).length],['Personas vinculadas',nPersonas],['Resultados del filtro',seleccion.length],['Promedio por responsable',Object.keys(grupos).length?(nPersonas/Object.keys(grupos).length).toFixed(1):'0'],['Grupos con 100 personas',Object.values(gruposVisibles()).filter(g=>g.cantidad===100).length],['Comunidades del filtro',estadistica.comunidades],[def.seguimiento+': Sí',estadistica.si],[def.seguimiento+': No',estadistica.no],['Seguimiento sin marcar',estadistica.pendiente]].map(([etiqueta,total])=>'<div class="panel"><strong>'+total+'</strong>'+e(etiqueta)+'</div>').join('');
  $('demografia').textContent='Vista '+(modo==='grupos'?'Responsables':'Personas')+': '+estadistica.hombres+' hombres · '+estadistica.mujeres+' mujeres · '+estadistica.otros+' otro / no indica · '+estadistica.sinGenero+' sin género declarado. Edad: '+estadistica.menores+' menores de 18 · '+estadistica.adultos+' de 18 a 59 · '+estadistica.mayores+' de 60 o más · '+estadistica.sinEdad+' sin fecha válida.';
  $('territorio-filas').innerHTML=estadistica.territorio.map((t,i)=>'<tr><td>'+e(t.parroquia)+'</td><td>'+e(t.comuna)+'</td><td>'+(modo==='personas'?'<button data-territorio="'+i+'">'+e(t.comunidad)+'</button>':e(t.comunidad))+'</td><td>'+t.total+'</td><td>'+t.responsables+'</td><td>'+t.si+'</td><td>'+t.no+'</td><td>'+t.pendiente+'</td></tr>').join('')||'<tr><td colspan="8">No hay registros en este ámbito.</td></tr>';
  $('territorio-filas').querySelectorAll('[data-territorio]').forEach(b=>b.onclick=()=>{const t=estadistica.territorio[Number(b.dataset.territorio)];$('parroquia').value=t.parroquia;actualizarOpciones();$('comuna').value=t.comuna;actualizarOpciones();$('comunidad').value=t.comunidad;pagina=1;pintar();$('total').scrollIntoView({block:'start',behavior:'smooth'});});
  $('estado').textContent=(verArchivados?'Mostrando grupos archivados · ':'')+(def.activo?'Recepción abierta':'Recepción cerrada')+' · Datos actualizados en vivo.'+(duplicadas?' Hay '+duplicadas+' vinculaciones con cédula repetida entre grupos; búscala para revisar responsables.':'');
  $('cabecera-tabla').innerHTML=`<tr><th>${modo==='grupos'?'Responsable':'Persona'}</th><th>Cédula</th><th>Teléfono</th><th>Fecha nac. / edad</th><th>Género</th><th>Comuna / comunidad</th><th>${modo==='grupos'?'Personas':'Responsable'}</th><th>Necesidad / observación</th><th>${e(def.seguimiento)}</th><th>Ficha</th></tr>`;
  $('filas').innerHTML=seleccion.slice((pagina-1)*25,pagina*25).map((r,i)=>`<tr><td>${e(C.nombre(r.persona))}</td><td>${e(C.documento(r.persona))}</td><td>${e(r.persona.telefono)}</td><td>${e(window.Formularios.mostrar({tipo:'fecha'},r.persona.fecha_nacimiento||''))}<small>${C.edad(r.persona.fecha_nacimiento)===null?'Edad sin dato':C.edad(r.persona.fecha_nacimiento)+' años'}</small></td><td>${e(r.persona.genero||'Sin dato')}</td><td>${e(r.persona.comuna)}<small>${e(r.persona.comunidad)}</small></td><td>${modo==='grupos'?'<button data-ficha="'+r.id+'">'+r.cantidad+' / 100 personas</button>':e(C.nombre(r.responsable))}</td><td>${e(r.persona.necesidad)}</td><td>${badge(r.estado)}<select aria-label="${e(def.seguimiento+' de '+C.nombre(r.persona))}" data-estado="${i}"><option value="">Sin marcar</option><option ${r.estado==='Sí'?'selected':''}>Sí</option><option ${r.estado==='No'?'selected':''}>No</option></select></td><td><button data-ficha="${r.id}">Ver grupo</button></td></tr>`).join('')||`<tr><td colspan="10">${cargados?'No hay registros que coincidan.':'Cargando registros…'}</td></tr>`;
  $('total').textContent=seleccion.length+' '+(modo==='grupos'?(seleccion.length===1?'responsable':'responsables'):(seleccion.length===1?'persona':'personas'));$('paginacion').textContent='Página '+pagina+' de '+max;$('anterior').disabled=pagina<=1;$('siguiente').disabled=pagina>=max;['excel','pdf','csv','pdf-resumen','pdf-asistencia','pdf-fichas'].forEach(k=>$(k).disabled=!seleccion.length);
  $('filas').querySelectorAll('[data-ficha]').forEach(b=>b.onclick=()=>ficha(b.dataset.ficha));$('filas').querySelectorAll('[data-estado]').forEach(s=>s.onchange=async()=>{const r=seleccion[(pagina-1)*25+Number(s.dataset.estado)];s.disabled=true;try{await set(ref(db,'censos_seguimiento/'+id+'/'+r.id+'/'+r.personaId),{valor:s.value,documento:C.documento(r.persona),actualizado_en:serverTimestamp(),por:user.uid});mensaje('Seguimiento guardado.','bien');}catch{mensaje('No se pudo guardar el seguimiento. Intenta de nuevo.','error');pintar();}finally{s.disabled=false;}});
}
function datosPersona(p,titulo){return `<section class="censo-ficha"><h3>${e(titulo)}</h3><dl>${C.campos.map(c=>`<div><dt>${e(c.etiqueta)}</dt><dd>${e(p[c.rol]?c.tipo==='fecha'?window.Formularios.mostrar(c,p[c.rol]):p[c.rol]:'Sin respuesta')}</dd></div>`).join('')}</dl></section>`;}
function ficha(key){const r=grupos[key];$('detalle').innerHTML=`<p>${r.cantidad} ${r.cantidad===1?'persona':'personas'} · Referencia ${key}</p><a class="boton primario" href="censo.html?id=${id}&grupo=${key}">Corregir grupo o agregar personas</a>`+datosPersona(r.responsable,'Responsable: '+C.nombre(r.responsable))+Object.values(r.personas).map((p,i)=>datosPersona(p,'Persona '+(i+1)+': '+C.nombre(p))).join('');let confirmarArchivo=false;$('detalle').insertAdjacentHTML('afterbegin','<button id="archivar-grupo">'+(r.archivado?'Restaurar grupo':'Archivar grupo')+'</button>');document.getElementById('archivar-grupo').onclick=async()=>{if(!r.archivado&&!confirmarArchivo){confirmarArchivo=true;document.getElementById('archivar-grupo').textContent='Confirmar archivo';mensaje('Se conservarán todas las fichas. Pulsa Confirmar archivo para retirarlo del listado activo; podrás restaurarlo después.');return;}try{await update(ref(db,'censos_grupos/'+id+'/'+key),{archivado:!r.archivado,actualizado_en:serverTimestamp()});$('ficha').close();mensaje(r.archivado?'Grupo restaurado.':'Grupo archivado. Puedes restaurarlo desde Ver archivados.','bien');}catch{mensaje('No se pudo cambiar el archivo del grupo.','error');}};$('ficha').showModal();}
function contexto(){return Object.entries(filtros()).filter(([,v])=>v).map(([k,v])=>k+': '+(k==='responsable'?C.nombre(grupos[v]?.responsable):v)).join(' · ')||'Todos los registros';}
function descargar(blob,nombre){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=nombre;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const informes=()=>window.CensoInformes.crear({C,XLSX:window.XLSX,JSZip:window.JSZip,jspdf:window.jspdf,dibujarHeaderPDF,dibujarFooterPDF});
const opcionesInforme=()=>({def,filas:seleccion,modo,grupos,seguimiento,contexto:contexto()});
async function excel(){try{const i=informes();descargar(await i.archivoExcel(i.libro(opcionesInforme())),'censo-'+modo+'.xlsx');}catch{mensaje('No se pudo generar el Excel. Comprueba la conexión a las bibliotecas de exportación.','error');}}
function csv(){descargar(new Blob([C.csv(C.tabla(seleccion,def.seguimiento,modo))],{type:'text/csv;charset=utf-8'}),'censo-'+modo+'.csv');}
function pdfAdicional(tipo){try{const op=opcionesInforme();if(tipo==='fichas'){op.filas=modo==='grupos'?C.filas(Object.fromEntries(Object.entries(grupos).filter(([k])=>seleccion.some(r=>r.id===k))),seguimiento):seleccion;}const i=informes(),doc=tipo==='resumen'?i.resumenPdf(op):tipo==='asistencia'?i.asistenciaPdf(op):i.fichasPdf(op);doc.save('censo-'+tipo+'.pdf');}catch{mensaje('No se pudo generar el informe. Comprueba las bibliotecas de PDF.','error');}}

function pdf(){try{const doc=new jspdf.jsPDF({unit:'mm',format:'letter'}),paginas=new Set();const header=()=>{const p=doc.internal.getCurrentPageInfo().pageNumber;if(!paginas.has(p)){dibujarHeaderPDF(doc,{titulo:'Censo municipal',subtitulo:'Responsables y personas'});paginas.add(p);}};header();doc.setFontSize(9);const intro=doc.splitTextToSize(def.titulo+' · '+new Date().toLocaleString('es-VE',{timeZone:'America/Caracas'})+' · '+contexto(),188);doc.text(intro,14,60);let y=66+intro.length*4;seleccion.forEach(r=>{const filas=[...C.campos.map(c=>['Responsable: '+c.etiqueta,r.responsable[c.rol]?c.tipo==='fecha'?window.Formularios.mostrar(c,r.responsable[c.rol]):r.responsable[c.rol]:'Sin respuesta']),...C.campos.map(c=>[(modo==='grupos'?'Ficha: ':'Persona: ')+c.etiqueta,r.persona[c.rol]?c.tipo==='fecha'?window.Formularios.mostrar(c,r.persona[c.rol]):r.persona[c.rol]:'Sin respuesta']),[def.seguimiento,r.estado||'Sin marcar'],['Personas en el grupo',String(r.cantidad)],['Referencia del grupo',r.id]];if(y>230){doc.addPage();header();y=58;}doc.autoTable({startY:y,head:[[modo==='grupos'?'Responsable':'Persona',C.nombre(r.persona)]],body:filas,margin:{top:58,bottom:22,left:14,right:14},styles:{fontSize:9,overflow:'linebreak',cellPadding:3},columnStyles:{0:{cellWidth:60},1:{cellWidth:127.9}},headStyles:{fillColor:[23,75,132]},didDrawPage:header});y=doc.lastAutoTable.finalY+10;});const total=doc.internal.getNumberOfPages();for(let p=1;p<=total;p++){doc.setPage(p);dibujarFooterPDF(doc);doc.setFillColor(255,255,255);const alto=doc.internal.pageSize.getHeight();doc.rect(176,alto-10,28,7,'F');doc.setFontSize(7);doc.text('Página '+p+' de '+total,202,alto-7,{align:'right'});}doc.save('censo-'+modo+'.pdf');}catch{mensaje('No se pudo generar el PDF. Comprueba la conexión a las bibliotecas de exportación.','error');}}
['buscar','parroquia','comuna','comunidad','responsable','seguimiento','genero','edad_min','edad_max'].forEach(k=>$(k).addEventListener(k==='buscar'?'input':'change',()=>{pagina=1;pintar();}));$('limpiar').onclick=()=>{['buscar','parroquia','comuna','comunidad','responsable','seguimiento','genero','edad_min','edad_max'].forEach(k=>$(k).value='');pagina=1;pintar();};document.querySelectorAll('[data-modo]').forEach(b=>b.onclick=()=>{modo=b.dataset.modo;pagina=1;document.querySelectorAll('[data-modo]').forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));pintar();});$('anterior').onclick=()=>{pagina--;pintar();};$('siguiente').onclick=()=>{pagina++;pintar();};$('cerrar-ficha').onclick=()=>$('ficha').close();$('excel').onclick=excel;$('pdf').onclick=pdf;$('csv').onclick=csv;$('archivo').onclick=()=>{verArchivados=!verArchivados;$('archivo').textContent=verArchivados?'Ver grupos activos':'Ver archivados';pagina=1;pintar();};$('pdf-resumen').onclick=()=>pdfAdicional('resumen');$('pdf-asistencia').onclick=()=>pdfAdicional('asistencia');$('pdf-fichas').onclick=()=>pdfAdicional('fichas');
try{id=idFormulario();user=await sesion();if(!await administrador(user))throw new Error('Inicia sesión con una cuenta de administrador.');def=(await get(ref(db,'censos_definiciones/'+id))).val();if(!def)throw new Error('No se encontró el censo.');if(user.email!==SUPER&&def.lectura!=='administradores')throw new Error('Este panel está reservado a Carlos.');$('carga').hidden=true;$('contenido').hidden=false;$('titulo').textContent=def.titulo;$('descripcion').textContent=def.descripcion;$('etiqueta-seguimiento').textContent=def.seguimiento;$('registrar').href='censo.html?id='+id;$('enlaces').innerHTML=enlaces(id);copiar($('enlaces'));$('compartir').onclick=()=>{$('enlaces').hidden=!$('enlaces').hidden;};onValue(ref(db,'censos_definiciones/'+id),s=>{def=s.val();if(!def){location.reload();return;}$('titulo').textContent=def.titulo;$('etiqueta-seguimiento').textContent=def.seguimiento;pintar();},()=>{mensaje('Tu acceso a este censo cambió. Recarga el panel.','error');$('contenido').hidden=true;});onValue(ref(db,'censos_grupos/'+id),s=>{grupos=s.val()||{};cargados=true;pintar();},()=>{mensaje('No se pudieron cargar los registros o cambió tu permiso. Recarga el panel.','error');$('contenido').hidden=true;});onValue(ref(db,'censos_seguimiento/'+id),s=>{seguimiento=s.val()||{};pintar();},()=>mensaje('No se pudo cargar el seguimiento.','error'));}catch(err){$('carga').hidden=true;mensaje(err.code?'No se pudo abrir el panel. Comprueba tu acceso.':err.message,'error');}
