import {db,ref,get,set,onValue,serverTimestamp,sesion,administrador,SUPER,idFormulario,mensaje} from './formularios-firebase.js';
import {enlaces,copiar} from './censo-ui.js';
import {dibujarHeaderPDF,dibujarFooterPDF} from './pdf-header.js';
const $=id=>document.getElementById(id),C=window.Censo,e=window.Formularios.escapar;let id,def,user,grupos={},seguimiento={},modo='personas',pagina=1,seleccion=[],cargados=false;
const filtros=()=>Object.fromEntries(['buscar','parroquia','comuna','comunidad','responsable','seguimiento'].map(k=>[k==='seguimiento'?'estado':k,$(k).value]));
function opciones(k,valores,texto='Todos'){const valor=$(k).value;$(k).innerHTML=`<option value="">${texto}</option>`+[...new Set(valores)].filter(Boolean).sort((a,b)=>a.localeCompare(b,'es')).map(v=>`<option value="${e(v)}">${e(v)}</option>`).join('');$(k).value=valor;}
function actualizarOpciones(){const rows=C.filas(grupos,seguimiento,modo);opciones('parroquia',rows.map(r=>r.persona.parroquia),'Todas');const parroquia=$('parroquia').value;const ambito=rows.filter(r=>!parroquia||r.persona.parroquia===parroquia);opciones('comuna',ambito.map(r=>r.persona.comuna),'Todas');opciones('comunidad',ambito.filter(r=>!$('comuna').value||r.persona.comuna===$('comuna').value).map(r=>r.persona.comunidad),'Todas');const anterior=$('responsable').value;$('responsable').innerHTML='<option value="">Todos</option>'+Object.entries(grupos).sort((a,b)=>C.nombre(a[1].responsable).localeCompare(C.nombre(b[1].responsable),'es')).map(([key,r])=>`<option value="${key}">${e(C.nombre(r.responsable)+' · '+C.documento(r.responsable))}</option>`).join('');$('responsable').value=anterior;}
function badge(v){return `<span class="${v==='Sí'?'badge-si':v==='No'?'badge-no':'estado'}">${e(v||'Sin marcar')}</span>`;}
function pintar(){actualizarOpciones();const todas=C.filas(grupos,seguimiento,modo);seleccion=C.filtrar(todas,filtros());const max=Math.max(1,Math.ceil(seleccion.length/25));pagina=Math.min(pagina,max);const nPersonas=Object.values(grupos).reduce((n,g)=>n+g.cantidad,0);const duplicadas=C.filas(grupos,seguimiento).length-new Set(C.filas(grupos,seguimiento).map(r=>C.documento(r.persona))).size;
  $('metricas').innerHTML=`<div class="panel"><strong>${Object.keys(grupos).length}</strong>Responsables</div><div class="panel"><strong>${nPersonas}</strong>Personas vinculadas</div><div class="panel"><strong>${seleccion.length}</strong>Resultados del filtro</div><div class="panel"><strong>${seleccion.filter(r=>r.estado==='Sí').length}</strong>${e(def.seguimiento)}: Sí</div>`;
  $('estado').textContent=(def.activo?'Recepción abierta':'Recepción cerrada')+' · Datos actualizados en vivo.'+(duplicadas?' Hay '+duplicadas+' vinculaciones con cédula repetida entre grupos; búscala para revisar responsables.':'');
  $('cabecera-tabla').innerHTML=`<tr><th>${modo==='grupos'?'Responsable':'Persona'}</th><th>Cédula</th><th>Teléfono</th><th>Comuna / comunidad</th><th>${modo==='grupos'?'Personas':'Responsable'}</th><th>Necesidad / observación</th><th>${e(def.seguimiento)}</th><th>Ficha</th></tr>`;
  $('filas').innerHTML=seleccion.slice((pagina-1)*25,pagina*25).map((r,i)=>`<tr><td>${e(C.nombre(r.persona))}</td><td>${e(C.documento(r.persona))}</td><td>${e(r.persona.telefono)}</td><td>${e(r.persona.comuna)}<small>${e(r.persona.comunidad)}</small></td><td>${modo==='grupos'?r.cantidad:e(C.nombre(r.responsable))}</td><td>${e(r.persona.necesidad)}</td><td>${badge(r.estado)}<select aria-label="${e(def.seguimiento+' de '+C.nombre(r.persona))}" data-estado="${i}"><option value="">Sin marcar</option><option ${r.estado==='Sí'?'selected':''}>Sí</option><option ${r.estado==='No'?'selected':''}>No</option></select></td><td><button data-ficha="${r.id}">Ver grupo</button></td></tr>`).join('')||`<tr><td colspan="8">${cargados?'No hay registros que coincidan.':'Cargando registros…'}</td></tr>`;
  $('total').textContent=seleccion.length+' '+(modo==='grupos'?'responsables':'personas');$('paginacion').textContent='Página '+pagina+' de '+max;$('anterior').disabled=pagina<=1;$('siguiente').disabled=pagina>=max;$('excel').disabled=$('pdf').disabled=!seleccion.length;
  $('filas').querySelectorAll('[data-ficha]').forEach(b=>b.onclick=()=>ficha(b.dataset.ficha));$('filas').querySelectorAll('[data-estado]').forEach(s=>s.onchange=async()=>{const r=seleccion[(pagina-1)*25+Number(s.dataset.estado)];s.disabled=true;try{await set(ref(db,'censos_seguimiento/'+id+'/'+r.id+'/'+r.personaId),{valor:s.value,documento:C.documento(r.persona),actualizado_en:serverTimestamp(),por:user.uid});mensaje('Seguimiento guardado.','bien');}catch{mensaje('No se pudo guardar el seguimiento. Intenta de nuevo.','error');pintar();}finally{s.disabled=false;}});
}
function datosPersona(p,titulo){return `<section class="censo-ficha"><h3>${e(titulo)}</h3><dl>${C.campos.map(c=>`<div><dt>${e(c.etiqueta)}</dt><dd>${e(p[c.rol]||'Sin respuesta')}</dd></div>`).join('')}</dl></section>`;}
function ficha(key){const r=grupos[key];$('detalle').innerHTML=`<p>${r.cantidad} personas · Referencia ${key}</p><a class="boton primario" href="censo.html?id=${id}&grupo=${key}">Corregir grupo o agregar personas</a>`+datosPersona(r.responsable,'Responsable: '+C.nombre(r.responsable))+Object.values(r.personas).map((p,i)=>datosPersona(p,'Persona '+(i+1)+': '+C.nombre(p))).join('');$('ficha').showModal();}
function contexto(){return Object.entries(filtros()).filter(([,v])=>v).map(([k,v])=>k+': '+(k==='responsable'?C.nombre(grupos[v]?.responsable):v)).join(' · ')||'Todos los registros';}
async function excel(){try{const t=C.tabla(seleccion,def.seguimiento,modo),wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet([[def.titulo],['Generado el '+new Date().toLocaleString('es-VE',{timeZone:'America/Caracas'})+' · '+contexto()],t.encabezados,...t.filas]);ws['!cols']=t.encabezados.map(()=>({wch:24}));ws['!autofilter']={ref:XLSX.utils.encode_range({s:{r:2,c:0},e:{r:t.filas.length+2,c:t.encabezados.length-1}})};XLSX.utils.book_append_sheet(wb,ws,modo==='grupos'?'Responsables':'Personas');const zip=await JSZip.loadAsync(XLSX.write(wb,{bookType:'xlsx',type:'array'}));const path='xl/worksheets/sheet1.xml';let xml=await zip.file(path).async('string');xml=xml.replace(/<sheetViews[\s\S]*?<\/sheetViews>/,'').replace('<sheetData>','<sheetViews><sheetView workbookViewId="0"><pane ySplit="3" topLeftCell="A4" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>');zip.file(path,xml);const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='censo-'+modo+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch{mensaje('No se pudo generar el Excel. Comprueba la conexión a las bibliotecas de exportación.','error');}}
function pdf(){try{const doc=new jspdf.jsPDF({unit:'mm',format:'letter'}),paginas=new Set();const header=()=>{const p=doc.internal.getCurrentPageInfo().pageNumber;if(!paginas.has(p)){dibujarHeaderPDF(doc,{titulo:'Censo municipal',subtitulo:'Responsables y personas'});paginas.add(p);}};header();doc.setFontSize(9);const intro=doc.splitTextToSize(def.titulo+' · '+new Date().toLocaleString('es-VE',{timeZone:'America/Caracas'})+' · '+contexto(),188);doc.text(intro,14,60);let y=66+intro.length*4;seleccion.forEach(r=>{const filas=[...C.campos.map(c=>['Responsable: '+c.etiqueta,r.responsable[c.rol]||'Sin respuesta']),...C.campos.map(c=>[(modo==='grupos'?'Ficha: ':'Persona: ')+c.etiqueta,r.persona[c.rol]||'Sin respuesta']),[def.seguimiento,r.estado||'Sin marcar'],['Personas en el grupo',String(r.cantidad)],['Referencia del grupo',r.id]];if(y>230){doc.addPage();header();y=58;}doc.autoTable({startY:y,head:[[modo==='grupos'?'Responsable':'Persona',C.nombre(r.persona)]],body:filas,margin:{top:58,bottom:22,left:14,right:14},styles:{fontSize:9,overflow:'linebreak',cellPadding:3},columnStyles:{0:{cellWidth:60},1:{cellWidth:127.9}},headStyles:{fillColor:[23,75,132]},didDrawPage:header});y=doc.lastAutoTable.finalY+10;});const total=doc.internal.getNumberOfPages();for(let p=1;p<=total;p++){doc.setPage(p);dibujarFooterPDF(doc);doc.setFillColor(255,255,255);const alto=doc.internal.pageSize.getHeight();doc.rect(176,alto-10,28,7,'F');doc.setFontSize(7);doc.text('Página '+p+' de '+total,202,alto-7,{align:'right'});}doc.save('censo-'+modo+'.pdf');}catch{mensaje('No se pudo generar el PDF. Comprueba la conexión a las bibliotecas de exportación.','error');}}
['buscar','parroquia','comuna','comunidad','responsable','seguimiento'].forEach(k=>$(k).addEventListener(k==='buscar'?'input':'change',()=>{pagina=1;pintar();}));$('limpiar').onclick=()=>{['buscar','parroquia','comuna','comunidad','responsable','seguimiento'].forEach(k=>$(k).value='');pagina=1;pintar();};document.querySelectorAll('[data-modo]').forEach(b=>b.onclick=()=>{modo=b.dataset.modo;pagina=1;document.querySelectorAll('[data-modo]').forEach(x=>x.setAttribute('aria-pressed',x===b?'true':'false'));pintar();});$('anterior').onclick=()=>{pagina--;pintar();};$('siguiente').onclick=()=>{pagina++;pintar();};$('cerrar-ficha').onclick=()=>$('ficha').close();$('excel').onclick=excel;$('pdf').onclick=pdf;
try{id=idFormulario();user=await sesion();if(!await administrador(user))throw new Error('Inicia sesión con una cuenta de administrador.');def=(await get(ref(db,'censos_definiciones/'+id))).val();if(!def)throw new Error('No se encontró el censo.');if(user.email!==SUPER&&def.lectura!=='administradores')throw new Error('Este panel está reservado a Carlos.');$('carga').hidden=true;$('contenido').hidden=false;$('titulo').textContent=def.titulo;$('descripcion').textContent=def.descripcion;$('etiqueta-seguimiento').textContent=def.seguimiento;$('registrar').href='censo.html?id='+id;$('enlaces').innerHTML=enlaces(id);copiar($('enlaces'));$('compartir').onclick=()=>{$('enlaces').hidden=!$('enlaces').hidden;};onValue(ref(db,'censos_definiciones/'+id),s=>{def=s.val();if(!def){location.reload();return;}$('titulo').textContent=def.titulo;$('etiqueta-seguimiento').textContent=def.seguimiento;pintar();},()=>{mensaje('Tu acceso a este censo cambió. Recarga el panel.','error');$('contenido').hidden=true;});onValue(ref(db,'censos_grupos/'+id),s=>{grupos=s.val()||{};cargados=true;pintar();},()=>{mensaje('No se pudieron cargar los registros o cambió tu permiso. Recarga el panel.','error');$('contenido').hidden=true;});onValue(ref(db,'censos_seguimiento/'+id),s=>{seguimiento=s.val()||{};pintar();},()=>mensaje('No se pudo cargar el seguimiento.','error'));}catch(err){$('carga').hidden=true;mensaje(err.code?'No se pudo abrir el panel. Comprueba tu acceso.':err.message,'error');}
