// parroquias-data.js — Estado -> Municipio -> [Parroquias] de toda Venezuela.
// Fuente: dataset publico basado en el CNE (github.com/zokeber/venezuela-json).
// La Guaira (Vargas, 11 parroquias) se mantiene EXACTAMENTE como el selector
// original de Hogares Solidarios (Sismo 2026). Define window.VENEZUELA.
window.VENEZUELA = {
  "Amazonas": {
    "Alto Orinoco": ["Alto Orinoco La Esmeralda","Huachamacare Acanaña","Marawaka Toky Shamanaña","Mavaka Mavaka","Sierra Parima Parimabé"],
    "Atabapo": ["Ucata Laja Lisa","Yapacana Macuruco","Caname Guarinuma"],
    "Atures": ["Fernando Girón Tovar","Luis Alberto Gómez","Pahueña Limón de Parhueña","Platanillal Platanillal"],
    "Autana": ["Samariapo Samariapo","Sipapo Pendare","Munduapo Munduapo","Guayapo San Pedro del Orinoco"],
    "Manapiare": ["Alto Ventuari Cacurí","Medio Ventuari Manami","Bajo Ventuari Marueta"],
    "Maroa": ["Victorino","Comunidad"],
    "Río Negro": ["Casiquiare Curimacare","Cocuy","San Carlos de Río Negro","Solano Solano"]
  },
  "Anzoátegui": {
    "Anaco": ["Anaco","San Joaquín"],
    "Aragua": ["Cachipo","Aragua de Barcelona"],
    "Bolívar": ["Bergatín","Caigua","El Carmen","El Pilar","Naricual","San Cristóbal"],
    "Bruzual": ["Clarines","Guanape","Sabana de Uchire"],
    "Cajigal": ["Onoto","San Pablo"],
    "Carvajal": ["Valle de Guanape","Santa Bárbara"],
    "Diego Bautista Urbaneja": ["Lechería","El Morro"],
    "Freites": ["Cantaura","Libertador","Santa Rosa","Urica"],
    "Guanipa": ["San José de Guanipa"],
    "Guanta": ["Guanta","Chorrerón"],
    "Independencia": ["Mamo","Soledad"],
    "Libertad": ["San Mateo","El Carito","Santa Inés","La Romereña"],
    "McGregor": ["El Chaparro","Tomás Alfaro","Calatrava"],
    "Miranda": ["Atapirire","Boca del Pao","El Pao","Pariaguán"],
    "Monagas": ["Mapire","Piar","Santa Clara","San Diego de Cabrutica","Uverito","Zuata"],
    "Peñalver": ["Puerto Píritu","San Miguel","Sucre"],
    "Píritu": ["Píritu","San Francisco"],
    "San Juan de Capistrano": ["Boca de Uchire","Boca de Chávez"],
    "Santa Ana": ["Pueblo Nuevo","Santa Ana"],
    "Simón Rodríguez": ["Edmundo Barrios","Miguel Otero Silva"],
    "Sotillo": ["Puerto La Cruz","Pozuelos"]
  },
  "Apure": {
    "Achaguas": ["Achaguas","Apurito","El Yagual","Guachara","Mucuritas","Queseras del medio"],
    "Biruaca": ["Biruaca"],
    "Muñoz": ["Bruzual","Mantecal","Quintero","Rincón Hondo","San Vicente"],
    "Páez": ["Guasdualito","Aramendi","El Amparo","San Camilo","Urdaneta"],
    "Pedro Camejo": ["San Juan de Payara","Codazzi","Cunaviche"],
    "Rómulo Gallegos": ["Elorza","La Trinidad"],
    "San Fernando": ["San Fernando","El Recreo","Peñalver","San Rafael de Atamaica"]
  },
  "Aragua": {
    "Bolívar": ["Bolívar"],
    "Camatagua": ["Camatagua","Carmen de Cura"],
    "Francisco Linares Alcántara": ["Santa Rita","Francisco de Miranda","Moseñor Feliciano González"],
    "Girardot": ["Pedro José Ovalles","Joaquín Crespo","José Casanova Godoy","Madre María de San José","Andrés Eloy Blanco","Los Tacarigua","Las Delicias","Choroní"],
    "José Ángel Lamas": ["Santa Cruz"],
    "José Félix Ribas": ["José Félix Ribas","Castor Nieves Ríos","Las Guacamayas","Pao de Zárate","Zuata"],
    "José Rafael Revenga": ["José Rafael Revenga"],
    "Libertador": ["Palo Negro","San Martín de Porres"],
    "Mario Briceño Iragorry": ["El Limón","Caña de Azúcar"],
    "Ocumare de la Costa de Oro": ["Ocumare de la Costa"],
    "San Casimiro": ["San Casimiro","Güiripa","Ollas de Caramacate","Valle Morín"],
    "San Sebastián": ["San Sebastián"],
    "Santiago Mariño": ["Turmero","Arevalo Aponte","Chuao","Samán de Güere","Alfredo Pacheco Miranda"],
    "Santos Michelena": ["Santos Michelena","Tiara"],
    "Sucre": ["Cagua","Bella Vista"],
    "Tovar": ["Tovar"],
    "Urdaneta": ["Urdaneta","Las Peñitas","San Francisco de Cara","Taguay"],
    "Zamora": ["Zamora","Magdaleno","San Francisco de Asís","Valles de Tucutunemo","Augusto Mijares"]
  },
  "Barinas": {
    "Alberto Arvelo Torrealba": ["Sabaneta","Juan Antonio Rodríguez Domínguez"],
    "Andrés Eloy Blanco": ["El Cantón","Santa Cruz de Guacas","Puerto Vivas"],
    "Antonio José de Sucre": ["Ticoporo","Nicolás Pulido","Andrés Bello"],
    "Arismendi": ["Arismendi","Guadarrama","La Unión","San Antonio"],
    "Barinas": ["Barinas","Alberto Arvelo Larriva","San Silvestre","Santa Inés","Santa Lucía","Torunos","El Carmen","Rómulo Betancourt","Corazón de Jesús","Ramón Ignacio Méndez","Alto Barinas","Manuel Palacio Fajardo","Juan Antonio Rodríguez Domínguez","Dominga Ortiz de Páez"],
    "Bolívar": ["Barinitas","Altamira de Cáceres","Calderas"],
    "Cruz Paredes": ["Barrancas","El Socorro","Mazparrito"],
    "Ezequiel Zamora": ["Santa Bárbara","Pedro Briceño Méndez","Ramón Ignacio Méndez","José Ignacio del Pumar"],
    "Obispos": ["Obispos","Los Guasimitos","El Real","La Luz"],
    "Pedraza": ["Ciudad Bolívia","José Ignacio Briceño","José Félix Ribas","Páez"],
    "Rojas": ["Libertad","Dolores","Santa Rosa","Palacio Fajardo","Simón Rodríguez"],
    "Sosa": ["Ciudad de Nutrias","El Regalo","Puerto Nutrias","Santa Catalina","Simón Bolívar"]
  },
  "Bolívar": {
    "Angostura": ["Raúl Leoni","Barceloneta","Santa Bárbara","San Francisco"],
    "Caroní": ["Cachamay","Chirica","Dalla Costa","Once de Abril","Simón Bolívar","Unare","Universidad","Vista al Sol","Pozo Verde","Yocoima","5 de Julio"],
    "Cedeño": ["Cedeño","Altagracia","Ascensión Farreras","Guaniamo","La Urbana","Pijiguaos"],
    "El Callao": ["El Callao"],
    "Gran Sabana": ["Gran Sabana","Ikabarú"],
    "Heres": ["Catedral","Zea","Orinoco","José Antonio Páez","Marhuanta","Agua Salada","Vista Hermosa","La Sabanita","Panapana"],
    "Píar": ["Andrés Eloy Blanco","Pedro Cova"],
    "Roscio": ["Roscio","Salóm"],
    "Sifontes": ["Sifontes","Dalla Costa","San Isidro"],
    "Sucre": ["Sucre","Aripao","Guarataro","Las Majadas","Moitaco"],
    "Padre Pedro Chien": ["Padre Pedro Chien","Río Grande"]
  },
  "Carabobo": {
    "Bejuma": ["Bejuma","Canoabo","Simón Bolívar"],
    "Carlos Arvelo": ["Güigüe","Carabobo","Tacarigua"],
    "Diego Ibarra": ["Mariara","Aguas Calientes"],
    "Guacara": ["Ciudad Alianza","Guacara","Yagua"],
    "Mora": ["Morón","Urama"],
    "Libertador": ["Valencia","Campo Carabobo"],
    "Los Guayos": ["Los Guayos"],
    "Miranda": ["Miranda"],
    "Montalbán": ["Montalbán"],
    "Naguanagua": ["Naguanagua"],
    "Puerto Cabello": ["Bartolomé Salóm","Democracia","Fraternidad","Goaigoaza","Juan José Flores","Unión","Borburata","Patanemo"],
    "San Diego": ["San Diego"],
    "San Joaquín": ["San Joaquín"],
    "Valencia": ["Urbana Candelaria","Urbana Catedral","Urbana El Socorro","Urbana Miguel Peña","Urbana Rafael Urdaneta","Urbana San Blas","Urbana San José","Urbana Santa Rosa","No Urbana Negro Primero"]
  },
  "Cojedes": {
    "Anzoátegui": ["Cojedes","Juan de Mata Suárez"],
    "Tinaquillo": ["Tinaquillo"],
    "Girardot": ["El Baúl","Sucre"],
    "Lima Blanco": ["La Aguadita","Macapo"],
    "Pao de San Juan Bautista": ["El Pao"],
    "Ricaurte": ["El Amparo","Libertad de Cojedes"],
    "Rómulo Gallegos": ["Rómulo Gallegos"],
    "San Carlos": ["San Carlos de Austria","Juan Ángel Bravo","Manuel Manrique"],
    "Tinaco": ["General en Jefe José Laurencio Silva"]
  },
  "Delta Amacuro": {
    "Antonio Díaz": ["Curiapo","Almirante Luis Brión","Francisco Aniceto Lugo Boca de Cuyubini","Manuel Renaud","Padre Barral","Santos de Abelgas"],
    "Casacoima": ["Imataca Moruca","Cinco de Julio Piacoa","Juan Bautista Arismendi","Manuel Piar Santa Catalina","Rómulo Gallegos"],
    "Pedernales": ["Pedernales","Luis Beltrán Prieto Figueroa"],
    "Tucupita": ["San José","José Vidal Marcano Caparal de Guara","Juan Millán","Leonardo Ruíz Pineda Paloma","Mariscal Antonio José de Sucre","Monseñor Argimiro García San Rafael","San Rafael","Virgen del Valle"]
  },
  "Falcón": {
    "Acosta": ["Capadare","La Pastora","Libertador","San Juan de los Cayos"],
    "Bolívar": ["Aracua","La Peña","San Luis"],
    "Buchivacoa": ["Bariro","Borojó","Capatárida","Guajiro","Seque","Zazárida","Valle de Eroa"],
    "Carirubana": ["Norte","Carirubana","Santa Ana","Urbana Punta Cardón"],
    "Colina": ["La Vela de Coro","Acurigua","Guaibacoa","Las Calderas","Macoruca"],
    "Dabajuro": ["Dabajuro"],
    "Democracia": ["Agua Clara","Avaria","Pedregal","Piedra Grande","Purureche"],
    "Falcón": ["Adaure","Adícora","Baraived","Buena Vista","Jadacaquiva","El Vínculo","El Hato","Moruy","Pueblo Nuevo"],
    "Federación": ["Agua Larga","Churuguara","El Paují","Independencia","Mapararí"],
    "Jacura": ["Agua Linda","Araurima","Jacura"],
    "Los Taques": ["Los Taques","Judibana"],
    "Manaure": ["Cacique Manaure"],
    "Mauroa": ["Mene de Mauroa","San Félix","Casigua"],
    "Miranda": ["Guzmán Guillermo","Mitare","Río Seco","Sabaneta","San Antonio","San Gabriel","Santa Ana"],
    "Monseñor Iturriza": ["Boca del Tocuyo","Chichiriviche","Tocuyo de la Costa"],
    "Palmasola": ["Palmasola"],
    "Petit": ["Cabure","Colina","Curimagua"],
    "Píritu": ["San José de la Costa","Píritu"],
    "San Francisco": ["Capital San Francisco"],
    "Sucre": ["Sucre","Pecaya"],
    "Silva": ["Tucacas","Boca de Aroa"],
    "Tocópero": ["Tocópero"],
    "Unión": ["El Charal","Las Vegas del Tuy","Santa Cruz de Bucaral"],
    "Urumaco": ["Bruzual","Urumaco"],
    "Zamora": ["Puerto Cumarebo","La Ciénaga","La Soledad","Pueblo Cumarebo","Zazárida"]
  },
  "Guárico": {
    "Camaguán": ["Camaguán","Puerto Miranda","Uverito"],
    "Chaguaramas": ["Chaguaramas"],
    "El Socorro": ["El Socorro"],
    "Infante": ["Valle de la Pascua","Espino"],
    "Las Mercedes": ["Las Mercedes","Cabruta","Santa Rita de Manapire"],
    "Mellado": ["El Sombrero","Sosa"],
    "Miranda": ["El Calvario","El Rastro","Guardatinajas","Capital Urbana Calabozo"],
    "Monagas": ["Altagracia de Orituco","San Rafael de Orituco","San Francisco Javier de Lezama","Paso Real de Macaira","Carlos Soublette","San Francisco de Macaira","Libertad de Orituco"],
    "Ortiz": ["San José de Tiznados","San Francisco de Tiznados","San Lorenzo de Tiznados","Ortiz"],
    "Ribas": ["Tucupido","San Rafael de Laya"],
    "Roscio": ["Cantagallo","San Juan de los Morros","Parapara"],
    "San Gerónimo de Guayabal": ["Guayabal","Cazorla"],
    "San José de Guaribe": ["San José de Guaribe","Uveral"],
    "Santa María de Ipire": ["Santa María de Ipire","Altamira"],
    "Zaraza": ["Unare","Zaraza"]
  },
  "Lara": {
    "Andrés Eloy Blanco": ["Quebrada Honda de Guache","Pío Tamayo","Yacambú"],
    "Crespo": ["Freitez","José María Blanco"],
    "Iribarren": ["Catedral","Concepción","El Cují","Juan de Villegas","Santa Rosa","Tamaca","Unión","Aguedo Felipe Alvarado","Buena Vista","Juárez"],
    "Jiménez": ["Juan Bautista Rodríguez","Cuara","Diego de Lozada","Paraíso de San José","San Miguel","Tintorero","José Bernardo Dorante","Coronel Mariano Peraza"],
    "Morán": ["Anzoátegui","Bolívar","Guárico","Hilario Luna y Luna","Humocaro Bajo","Humocaro Alto","La Candelaria","Morán"],
    "Palavecino": ["Cabudare","José Gregorio Bastidas","Agua Viva"],
    "Simón Planas": ["Buría","Gustavo Vega","Sarare"],
    "Torres": ["Altagracia","Antonio Díaz","Camacaro","Castañeda","Cecilio Zubillaga","Chiquinquira","El Blanco","Espinoza de los Monteros","Heriberto Arrollo","Lara","Las Mercedes","Manuel Morillo","Montaña Verde","Montes de Oca","Reyes de Vargas","Torres","Trinidad Samuel"],
    "Urdaneta": ["Siquisique","San Miguel","Moroturo","Xaguas"]
  },
  "Mérida": {
    "Alberto Adriani": ["Presidente Betancourt","Presidente Páez","Presidente Rómulo Gallegos","Gabriel Picón González","Héctor Amable Mora","José Nucete Sardi","Pulido Méndez"],
    "Andrés Bello": ["La Azulita"],
    "Antonio Pinto Salinas": ["Santa Cruz de Mora","Mesa Bolívar","Mesa de Las Palmas"],
    "Aricagua": ["Aricagua","San Antonio"],
    "Arzobispo Chacón": ["Canagua","Capurí","Chacantá","El Molino","Guaimaral","Mucutuy","Mucuchachí"],
    "Campo Elías": ["Fernández Peña","Matriz","Montalbán","Acequias","Jají","La Mesa","San José del Sur"],
    "Caracciolo Parra Olmedo": ["Tucaní","Florencio Ramírez"],
    "Cardenal Quintero": ["Santo Domingo","Las Piedras"],
    "Guaraque": ["Guaraque","Mesa de Quintero","Río Negro"],
    "Julio César Salas": ["Arapuey","Palmira"],
    "Justo Briceño": ["San Cristóbal de Torondoy","Torondoy"],
    "Libertador": ["Antonio Spinetti Dini","Arias","Caracciolo Parra Pérez","Domingo Peña","El Llano","Gonzalo Picón Febres","Jacinto Plaza","Juan Rodríguez Suárez","Lasso de la Vega","Mariano Picón Salas","Milla","Osuna Rodríguez","Sagrario","El Morro","Los Nevados"],
    "Miranda": ["Andrés Eloy Blanco","La Venta","Piñango","Timotes"],
    "Obispo Ramos de Lora": ["Eloy Paredes","San Rafael de Alcázar","Santa Elena de Arenales"],
    "Padre Noguera": ["Santa María de Caparo"],
    "Pueblo Llano": ["Pueblo Llano"],
    "Rangel": ["Cacute","La Toma","Mucuchíes","Mucurubá","San Rafael"],
    "Rivas Dávila": ["Gerónimo Maldonado","Bailadores"],
    "Santos Marquina": ["Tabay"],
    "Sucre": ["Chiguará","Estánquez","Lagunillas","La Trampa","Pueblo Nuevo del Sur","San Juan"],
    "Tovar": ["El Amparo","El Llano","San Francisco","Tovar"],
    "Tulio Febres Cordero": ["Independencia","María de la Concepción Palacios Blanco","Nueva Bolivia","Santa Apolonia"],
    "Zea": ["Caño El Tigre","Zea"]
  },
  "Miranda": {
    "Acevedo": ["Aragüita","Arévalo González","Capaya","Caucagua","Panaquire","Ribas","El Café","Marizapa"],
    "Andrés Bello": ["Cumbo","San José de Barlovento"],
    "Baruta": ["El Cafetal","Las Minas","Nuestra Señora del Rosario"],
    "Brión": ["Higuerote","Curiepe","Tacarigua de Brión"],
    "Buroz": ["Mamporal"],
    "Carrizal": ["Carrizal"],
    "Chacao": ["Chacao"],
    "Cristóbal Rojas": ["Charallave","Las Brisas"],
    "El Hatillo": ["El Hatillo"],
    "Guaicaipuro": ["Altagracia de la Montaña","Cecilio Acosta","Los Teques","El Jarillo","San Pedro","Tácata","Paracotos"],
    "Independencia": ["Cartanal","Santa Teresa del Tuy"],
    "Lander": ["La Democracia","Ocumare del Tuy","Santa Bárbara"],
    "Los Salias": ["San Antonio de los Altos"],
    "Páez": ["Río Chico","El Guapo","Tacarigua de la Laguna","Paparo","San Fernando del Guapo"],
    "Paz Castillo": ["Santa Lucía del Tuy"],
    "Pedro Gual": ["Cúpira","Machurucuto"],
    "Plaza": ["Guarenas"],
    "Simón Bolívar": ["San Antonio de Yare","San Francisco de Yare"],
    "Sucre": ["Leoncio Martínez","Petare","Caucagüita","Filas de Mariche","La Dolorita"],
    "Urdaneta": ["Cúa","Nueva Cúa"],
    "Zamora": ["Guatire","Bolívar"]
  },
  "Monagas": {
    "Acosta": ["San Antonio de Maturín","San Francisco de Maturín"],
    "Aguasay": ["Aguasay"],
    "Bolívar": ["Caripito"],
    "Caripe": ["El Guácharo","La Guanota","Sabana de Piedra","San Agustín","Teresen","Caripe"],
    "Cedeño": ["Areo","Capital Cedeño","San Félix de Cantalicio","Viento Fresco"],
    "Ezequiel Zamora": ["El Tejero","Punta de Mata"],
    "Libertador": ["Chaguaramas","Las Alhuacas","Tabasca","Temblador"],
    "Maturín": ["Alto de los Godos","Boquerón","Las Cocuizas","La Cruz","San Simón","El Corozo","El Furrial","Jusepín","La Pica","San Vicente"],
    "Piar": ["Aparicio","Aragua de Maturín","Chaguamal","El Pinto","Guanaguana","La Toscana","Taguaya"],
    "Punceres": ["Cachipo","Quiriquire"],
    "Santa Bárbara": ["Santa Bárbara"],
    "Sotillo": ["Barrancas","Los Barrancos de Fajardo"],
    "Uracoa": ["Uracoa"]
  },
  "Nueva Esparta": {
    "Antolín del Campo": ["Antolín del Campo"],
    "Arismendi": ["Arismendi"],
    "Díaz": ["San Juan Bautista","Zabala"],
    "García": ["García","Francisco Fajardo"],
    "Gómez": ["Bolívar","Guevara","Cerro de Matasiete","Santa Ana","Sucre"],
    "Maneiro": ["Aguirre","Maneiro"],
    "Marcano": ["Adrián","Juan Griego","Yaguaraparo"],
    "Mariño": ["Porlamar"],
    "Península de Macanao": ["San Francisco de Macanao","Boca de Río"],
    "Tubores": ["Tubores","Los Barales"],
    "Villalba": ["Vicente Fuentes","Villalba"]
  },
  "Portuguesa": {
    "Agua Blanca": ["Agua Blanca"],
    "Araure": ["Araure","Río Acarigua"],
    "Esteller": ["Píritu","Uveral"],
    "Guanare": ["Cordova","Guanare","San José de la Montaña","San Juan de Guanaguanare","Virgen de Coromoto"],
    "Guanarito": ["Guanarito","Trinidad de la Capilla","Divina Pastora"],
    "Monseñor José Vicente de Unda": ["Peña Blanca"],
    "Ospino": ["Aparición","La Estación","Ospino"],
    "Páez": ["Acarigua","Payara","Pimpinela","Ramón Peraza"],
    "Papelón": ["Caño Delgadito","Papelón"],
    "San Genaro de Boconoíto": ["Antolín Tovar Anquino","Boconoíto"],
    "San Rafael de Onoto": ["Santa Fé","San Rafael de Onoto","Thermo Morales"],
    "Santa Rosalía": ["Florida","El Playón"],
    "Sucre": ["Biscucuy","Concepción","San José de Saguaz","San Rafael de Palo Alzado","Uvencio Antonio Velásquez","Villa Rosa"],
    "Turén": ["Canelones","Santa Cruz","San Isidro Labrador"]
  },
  "Sucre": {
    "Andrés Eloy Blanco": ["Mariño","Rómulo Gallegos"],
    "Andrés Mata": ["San José de Aerocuar","Tavera Acosta"],
    "Arismendi": ["Río Caribe","Antonio José de Sucre","El Morro de Puerto Santo","Puerto Santo","San Juan de las Galdonas"],
    "Benítez": ["El Pilar","El Rincón","General Francisco Antonio Váquez","Guaraúnos","Tunapuicito","Unión"],
    "Bermúdez": ["Santa Catalina","Santa Rosa","Santa Teresa","Bolívar","Maracapana"],
    "Bolívar": [],
    "Cajigal": ["Libertad","El Paujil","Yaguaraparo"],
    "Cruz Salmerón Acosta": ["Cruz Salmerón Acosta","Chacopata","Manicuare"],
    "Libertador": ["Tunapuy","Campo Elías"],
    "Mariño": ["Irapa","Campo Claro","Maraval","San Antonio de Irapa","Soro"],
    "Mejía": ["Mejía"],
    "Montes": ["Cumanacoa","Arenas","Aricagua","Cocollar","San Fernando","San Lorenzo"],
    "Ribero": ["Villa Frontado (Muelle de Cariaco)","Catuaro","Rendón","San Cruz","Santa María"],
    "Sucre": ["Altagracia Cumaná","Santa Inés Cumaná","Valentín Valiente Cumaná","Ayacucho Cumaná","San Juan","Raúl Leoni","Gran Mariscal"],
    "Valdez": ["Cristóbal Colón","Bideau","Punta de Piedras","Güiria"]
  },
  "Táchira": {
    "Andrés Bello": ["Andrés Bello"],
    "Antonio Rómulo Costa": ["Antonio Rómulo Costa"],
    "Ayacucho": ["Ayacucho","Rivas Berti","San Pedro del Río"],
    "Bolívar": ["Bolívar","Palotal","General Juan Vicente Gómez","Isaías Medina Angarita"],
    "Cárdenas": ["Cárdenas","Amenodoro Rangel Lamus","La Florida"],
    "Córdoba": ["Córdoba"],
    "Fernández Feo": ["Fernández Feo","Alberto Adriani","Santo Domingo"],
    "Francisco de Miranda": ["Francisco de Miranda"],
    "García de Hevia": ["García de Hevia","Boca de Grita","José Antonio Páez"],
    "Guásimos": ["Guásimos"],
    "Independencia": ["Independencia","Juan Germán Roscio","Román Cárdenas"],
    "Jáuregui": ["Jáuregui","Emilio Constantino Guerrero","Monseñor Miguel Antonio Salas"],
    "José María Vargas": ["José María Vargas"],
    "Junín": ["Junín","La Petrólea","Quinimarí","Bramón"],
    "Libertad": ["Libertad","Cipriano Castro","Manuel Felipe Rugeles"],
    "Libertador": ["Capital Libertador","Doradas","Emeterio Ochoa","San Joaquín de Navay"],
    "Lobatera": ["Lobatera","Constitución"],
    "Michelena": ["Michelena"],
    "Panamericano": ["Panamericano","La Palmita"],
    "Pedro María Ureña": ["Pedro María Ureña","Nueva Arcadia"],
    "Rafael Urdaneta": ["Delicias","Pecaya"],
    "Samuel Darío Maldonado": ["Samuel Darío Maldonado","Boconó","Hernández"],
    "San Cristóbal": ["La Concordia","San Juan Bautista","Pedro María Morantes","San Sebastián","Dr. Francisco Romero Lobo"],
    "Seboruco": ["Seboruco"],
    "Simón Rodríguez": ["Simón Rodríguez"],
    "Sucre": ["Sucre","Eleazar López Contreras","San Pablo"],
    "Torbes": ["San José Obrero","San Juan Eudes"],
    "Uribante": ["Uribante","Cárdenas","Juan Pablo Peñalosa","Potosí"],
    "San Judas Tadeo": ["San Judas Tadeo"]
  },
  "Trujillo": {
    "Andrés Bello": ["Araguaney","El Jaguito","La Esperanza","Santa Isabel"],
    "Boconó": ["Boconó","El Carmen","Mosquey","Ayacucho","Burbusay","General Ribas","Guaramacal","Vega de Guaramacal","Monseñor Jáuregui","Rafael Rangel","San Miguel","San José"],
    "Bolívar": ["Sabana Grande","Cheregüé","Granados"],
    "Candelaria": ["Arnoldo Gabaldón","Bolivia","Carrillo","Cegarra","Chejendé","Manuel Salvador Ulloa","San José"],
    "Carache": ["Carache","La Concepción","Cuicas","Panamericana","Santa Cruz"],
    "Escuque": ["Escuque","La Unión (El Alto Escuque)","Santa Rita","Sabana Libre"],
    "José Felipe Márquez Cañizalez": ["El Socorro","Los Caprichos","Antonio José de Sucre"],
    "Juan Vicente Campos Elías": ["Campo Elías","Arnoldo Gabaldón"],
    "La Ceiba": ["Santa Apolonia","El Progreso","La Ceiba","Tres de Febrero"],
    "Miranda": ["El Dividive","Agua Santa","Agua Caliente","El Cenizo","Valerita"],
    "Monte Carmelo": ["Monte Carmelo","Buena Vista","Santa María del Horcón"],
    "Motatán": ["Motatán","El Baño","Jalisco"],
    "Pampán": ["Pampán","Flor de Patria","La Paz","Santa Ana"],
    "Pampanito": ["Pampanito","La Concepción","Pampanito II"],
    "Rafael Rangel": ["Betijoque","José Gregorio Hernández","La Pueblita","Los Cedros"],
    "San Rafael de Carvajal": ["Carvajal","Campo Alegre","Antonio Nicolás Briceño","José Leonardo Suárez"],
    "Sucre": ["Sabana de Mendoza","Junín","Valmore Rodríguez","El Paraíso"],
    "Trujillo": ["Andrés Linares","Chiquinquirá","Cristóbal Mendoza","Cruz Carrillo","Matriz","Monseñor Carrillo","Tres Esquinas"],
    "Urdaneta": ["Cabimbú","Jajó","La Mesa de Esnujaque","Santiago","Tuñame","La Quebrada"],
    "Valera": ["Juan Ignacio Montilla","La Beatriz","La Puerta","Mendoza del Valle de Momboy","Mercedes Díaz","San Luis"]
  },
  "La Guaira": {
    "Vargas": ["Catia La Mar","Carlos Soublette","Urimare","Maiquetía","La Guaira","Macuto","Caraballeda","Naiguatá","Caruao","Carayaca","El Junko"]
  },
  "Yaracuy": {
    "Arístides Bastidas": ["Arístides Bastidas"],
    "Bolívar": ["Bolívar"],
    "Bruzual": ["Chivacoa","Campo Elías"],
    "Cocorote": ["Cocorote"],
    "Independencia": ["Independencia"],
    "José Antonio Páez": ["José Antonio Páez"],
    "La Trinidad": ["La Trinidad"],
    "Manuel Monge": ["Manuel Monge"],
    "Nirgua": ["Salóm","Temerla","Nirgua"],
    "Peña": ["San Andrés","Yaritagua"],
    "San Felipe": ["San Javier","Albarico","San Felipe"],
    "Sucre": ["Sucre"],
    "Urachiche": ["Urachiche"],
    "Veroes": ["El Guayabo","Farriar"]
  },
  "Zulia": {
    "Almirante Padilla": ["Isla de Toas","Monagas"],
    "Baralt": ["General Urdaneta","Libertador","Marcelino Briceño","Pueblo Nuevo","Manuel Guanipa Matos"],
    "Cabimas": ["Ambrosio","Carmen Herrera","La Rosa","Germán Ríos Linares","San Benito","Rómulo Betancourt","Jorge Hernández","Punta Gorda","Arístides Calvani"],
    "Catatumbo": ["Encontrados","Udón Pérez"],
    "Colón": ["Moralito","San Carlos del Zulia","Santa Cruz del Zulia","Santa Bárbara","Urribarrí"],
    "Francisco Javier Pulgar": ["Carlos Quevedo","Francisco Javier Pulgar","Simón Rodríguez","Guamo-Gavilanes"],
    "Páez": ["Sinamaica","Alta Guajira","Elías Sánchez Rubio","Guajira"],
    "Jesús Enrique Lossada": ["La Concepción","San José","Mariano Parra León","José Ramón Yépez"],
    "Jesús María Semprún": ["Jesús María Semprún","Barí"],
    "La Cañada de Urdaneta": ["Concepción","Andrés Bello","Chiquinquirá","El Carmelo","Potreritos"],
    "Lagunillas": ["Libertad","Alonso de Ojeda","Venezuela","Eleazar López Contreras","Campo Lara"],
    "Machiques de Perijá": ["Bartolomé de las Casas","Libertad","Río Negro","San José de Perijá"],
    "Mara": ["San Rafael","La Sierrita","Las Parcelas","Luis de Vicente","Monseñor Marcos Sergio Godoy","Ricaurte","Tamare"],
    "Maracaibo": ["Antonio Borjas Romero","Bolívar","Cacique Mara","Carracciolo Parra Pérez","Cecilio Acosta","Cristo de Aranza","Coquivacoa","Chiquinquirá","Francisco Eugenio Bustamante","Idelfonzo Vásquez","Juana de Ávila","Luis Hurtado Higuera","Manuel Dagnino","Olegario Villalobos","Raúl Leoni","Santa Lucía","Venancio Pulgar","San Isidro"],
    "Miranda": ["Altagracia","Faría","Ana María Campos","San Antonio","San José"],
    "Rosario de Perijá": ["Donaldo García","El Rosario","Sixto Zambrano"],
    "San Francisco": ["San Francisco","El Bajo","Domitila Flores","Francisco Ochoa","Los Cortijos","Marcial Hernández"],
    "Santa Rita": ["Santa Rita","El Mene","Pedro Lucas Urribarrí","José Cenobio Urribarrí"],
    "Simón Bolívar": ["Rafael Maria Baralt","Manuel Manrique","Rafael Urdaneta"],
    "Sucre": ["Bobures","Gibraltar","Heras","Monseñor Arturo Álvarez","Rómulo Gallegos","El Batey"],
    "Valmore Rodríguez": ["Rafael Urdaneta","La Victoria","Raúl Cuenca"]
  },
  "Distrito Capital": {
    "Libertador": ["23 de enero","Altagracia","Antímano","Caricuao","Catedral","Coche","El Junquito","El Paraíso","El Recreo","El Valle","Candelaria","La Pastora","La Vega","Macarao","San Agustín","San Bernardino","San José","San Juan","San Pedro","Santa Rosalía","Santa Teresa","Sucre (Catia)"]
  }
};
